# Generated by Django 6.0.7 on 2026-07-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Confession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("content", models.TextField(max_length=1500)),
                ("attachment", models.URLField(max_length=2048, null=True)),
                ("spoiler", models.BooleanField(default=False)),
                ("reports", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "confession",
                "managed": True,
            },
        ),
    ]
