# Generated by Django 6.0.7 on 2026-07-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
            ],
            options={
                "db_table": "botadmin",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="confession",
            name="message_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
