# Generated by Django 6.0.7 on 2026-07-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_botadmin_confession_message_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="confession",
            name="spoiler",
        ),
        migrations.AddField(
            model_name="confession",
            name="spoiler_text",
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
