# Generated by Django 6.0.7 on 2026-08-01 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0003_remove_confession_spoiler_confession_spoiler_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="confession",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                (
                    "confession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.confession",
                    ),
                ),
            ],
            options={
                "db_table": "like",
                "managed": True,
                "indexes": [
                    models.Index(fields=["confession"], name="like_confess_10c79a_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "confession"), name="unique_like"
                    )
                ],
            },
        ),
    ]
